# Copyright (c) 2015-2018, Gregory M. Kurtzer. All rights reserved.
# 
# "Singularity" Copyright (c) 2018, The Regents of the University of California,
# through Lawrence Berkeley National Laboratory (subject to receipt of any
# required approvals from the U.S. Dept. of Energy).  All rights reserved.

BootStrap: debootstrap
OSVersion: xenial
MirrorURL: http://us.archive.ubuntu.com/ubuntu/

%files
    tensorflow.sh
    
%runscript
    exec /usr/bin/python "$@"

%environment
    LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH
    export LD_LIBRARY_PATH

%post
    . tensorflow.sh
    
    mkdir /scratch

    sed -i 's/$/ universe/' /etc/apt/sources.list
    
    apt-get update 
    
    apt-get -y --force-yes install vim \
                                   nano \
                                   curl \
                                   libfreetype6-dev \
                                   libpng12-dev \
                                   libzmq3-dev \
                                   python-numpy \
                                   python-pip \
                                   python-scipy && \
                              apt-get clean
